# Use a base image with Java
FROM openjdk:11-jre-slim

# Set the working directory
WORKDIR /app

# Copy the packaged JAR file into the container
COPY target/springgatewaydemo1-0.0.1-SNAPSHOT.jar app.jar

# Expose the port your application runs on

EXPOSE 8087


# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
